spring:
  datasource:
    url: jdbc:mysql://localhost:3306/swamedia   # JDBC URL for MySQL
    username: root                # Your MySQL username
    password: pass                # Your MySQL password
    driver-class-name: com.mysql.cj.jdbc.Driver          # MySQL JDBC driver class

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 3000                         # Port on which your application will run

# Additional application-specific properties can be added here
